- name: start autofs
  ansible.builtin.systemd_service:
    name: autofs
    state: started
    enabled: true
  when: 
  - nfs_mount_type == 'autofs'
  - state == 'present'

- name: config autofs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
  with_items: "{{ autofs_files }}"
  when: 
  - nfs_mount_type == 'autofs'
  - state == 'present'
  notify: restart autofs service